POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsYW5AZXhhbXBsZS5jb20iLCJleHAiOjE3MzA0NzIwMzQsInVzZXJJZCI6MTR9.TEk38loIQrFGJVPdPmobi0Y6zvNqKifH_QeGBprTqTo

{
    "name": "Testing REST AUTH",
    "description": "Final Fantasy XXI",
    "location": "Dargneel",
    "dateTime" : "2025-01-01T15:30:00.00Z"
}